### PR TITLE
update package versions

### PR DESCRIPTION
**Pull request by enricostrijks**

### CODE REVIEW

**Comment by Fudal** [comment]
@Larpoux can you merge it?

**Comment by Larpoux** [comment]
There is actually a big problem for this project :
One or two years ago, I tried to federate several developers to maintain this project.
I was unsuccessful and I have continued to work alone on Flutter-Sound. I really do not like that.

I have stopped to work on this project for more than one year (maybe two), and nobody wants to maintain it.
Actually I do not work anymore withe Flutter : ( I use Vue.js, now, and Svelte.js ).

I have not declared Flutter-Sound as a discontinued project, because I feel that there are still some developers using it, but it is really urgent to have a new project manager for Flutter Sound.

Please, note that Flutter-Sound father is not me, but @hyochan. I do not know if he wants to transfer the Flutter-Sound maintenance to someone else. I am afraid that he switched to React-Native and that he is not concerned anymore with Flutter-Sound.

I have no problem to transfer all the maintenance rights to anybody, but I do not have any experience to evaluate if someone is serious enough, and will dot drive the project to the wall. (Probably that the risk is not more than having nobody maintaining the project during several years).

I am going now to look to the various PR, and I will see if its OK to merge them (ore some of them) and if it is not too much work for me.

I will post something else when I will be more clear.

**Comment by Larpoux** [comment]
@enricostrijks , @Fudal 
Thank you @enricostrijks  for your contribution.
Your Pull Request is merged into Flutter Sound 9.3.6.


Please not that I found some minor bugs that I will fix in next release (in a few days): 

[issue 1010](https://github.com/Canardoux/flutter_sound/issues/1010)
[issue 1011](https://github.com/Canardoux/flutter_sound/issues/1011)
[issue 1011](https://github.com/Canardoux/flutter_sound/issues/1011)

**Comment by Larpoux** [comment]
@enricostrijks , @Fudal 
Thank you @enricostrijks  for your contribution.
Your Pull Request is merged into Flutter Sound 9.3.6.


Please not that I found some minor bugs that I will fix in next release (in a few days): 

[issue 1010](https://github.com/Canardoux/flutter_sound/issues/1010)
[issue 1011](https://github.com/Canardoux/flutter_sound/issues/1011)
[issue 1011](https://github.com/Canardoux/flutter_sound/issues/1011)

**Pull request closed without merging**
