### PR TITLE
bug fix: able to run example on ios and android

### PR DESCRIPTION
**Pull request by changcw83**

### CODE REVIEW

**Comment by Larpoux** [comment]
Hi my friend Chang. I have a conflict with your last Pull Request.
I don't understand why, with `flutter_sound_core`. I cannot help.
Do you think you can resolve this conflict yourself ?

**Comment by changcw83** [comment]
Sure, no problem.

**Comment by Larpoux** [comment]
I have still an error on FlutterSoundWeb : 
```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   packages/flutter_sound/public/flutter_sound_player.dart 1294:5                  _setVolumePan
│ #1   packages/flutter_sound/public/flutter_sound_player.dart 1293:29                 [_setVolumePan]
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 FS:---> setVolumePan 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3                   throw_
packages/flutter_sound_platform_interface/flutter_sound_player_platform_interface.dart 214:5  setVolumePan
packages/flutter_sound/public/flutter_sound_player.dart 1306:59                               _setVolumePan
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                                          runUnary
dart-sdk/lib/async/future_impl.dart 163:18                                                    handleValue
dart-sdk/lib/async/future_impl.dart 861:44                                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 890:13                                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 666:5                                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 736:7                                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                            <fn>
```

**Comment by changcw83** [comment]
ok i haven't tested on web shall try to make it work

**Comment by changcw83** [comment]
pushed the required change

**Comment by Larpoux** [comment]
There is still a problem on iOS : 
```
   - NOTE  | [iOS] xcodebuild:  note: Target dependency graph (3 targets)
    - WARN  | xcodebuild:  flutter_sound_core/ios/Classes/FlautoPlayerEngine.mm:565:9: warning: conflicting return type in implementation of 'setPan:': 'void' vs 'bool' [-Wmismatched-return-types]
    - NOTE  | xcodebuild:  flutter_sound_core/ios/Classes/FlautoPlayerEngine.h:113:8: note: previous definition is here
    - NOTE  | [iOS] xcodebuild:  note: Signing static framework with --generate-pre-encrypt-hashes (in target 'Pods-App' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'flutter_sound_core' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'Pods-App' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'App' from project 'App')

[!] The spec did not pass validation, due to 1 warning (but you can use `--allow-warnings` to ignore it).
```

**Comment by changcw83** [comment]
Fixed!

**Pull request merged**
