### PR TITLE
Fixes an issue in FlutterSoundPlayer -init:playerManager:  where the …

### PR DESCRIPTION
**Pull request by timcschmidt**
…voiceProcessing argument is always evaluated as true.

### CODE REVIEW

**Comment by timcschmidt** [comment]
This prevents mere playback requesting microphone access on ios.

**Comment by Larpoux** [comment]
Thank you @timcschmidt for your contribution. I really appreciate.
There is clearly a bug there.

My problem is now that when I call 
```
if (![outputNode setVoiceProcessingEnabled:YES error:&err])
```
then, later, when I call 
```
[engine connect: playerNode to: outputNode format: outputFormat];
```
I get an exception "required condition is false: IsFormatSampleRateAndChannelCountValid(format)"

I am not sure that this is tied with your patch. But I do not really understand the iOS library.
If you have an idea of what is happening I would be grateful.

**Comment by Larpoux** [comment]
in another test 
when I call : 
```
     AVAudioInputNode* inputNode = [engine inputNode];
     AVAudioFormat* inputFormat = [inputNode outputFormatForBus: 0];
     double sRate = [inputFormat sampleRate];
```
I get "sRate is 0" which is not correct.

**Comment by Larpoux** [comment]
My feeling is that those two errors are not tied to your patch.
But I do not thing iOS library is very understandable . I am lost.

**Comment by Larpoux** [comment]
Thank you again @timcschmidt for your contribution.
Your patch seems correct and it is now merged into Flutter Sound 9.3.8,
So I am closing your PR.
If you can look to #1019 I would be grateful.

**Pull request closed without merging**
